### PR TITLE
Fix email regex

### LINKED ISSUE #36: B: Regex for email validation is wrong
Valid email that gets flagged as invalid:
- wwwexample@gmail.com
- wwwww@yahoo.com

https://github.com/KingdomFirst/Bulldozer/blob/43dedb2570378bfaad9e6688fd550d474bda11c5/Bulldozer/Utility/Extensions.cs#L150

### PR DESCRIPTION
**Pull request by lauweijie**
Fixes #36.

Regex source: https://stackoverflow.com/a/16168103

##### What does the change add or fix in a succinct statement that will be read by clients?

- Fix email validation regex

### CODE REVIEW

**Comment by lauweijie** [comment]
Any updates to this?

File: Bulldozer/Utility/Extensions.cs [hunk 1]
```diff
@@ -147,7 +147,7 @@ public static string RemoveWhitespace( this string str )
         /// <returns>true if valid email, false otherwise</returns>
         public static bool IsEmail( this string email )
         {
-            return Regex.IsMatch( email, @"^(?!((http|https)://|www.))[\w\.\'_%-]+(\+[\w-]*)?@([\w-]+\.)+[\w-]+$" );
+            return Regex.IsMatch( emailString, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexOptions.IgnoreCase );
```
Comment (nateh777) [inline Bulldozer/Utility/Extensions.cs:150]:
```suggestion
            return Regex.IsMatch( email, @"^(?!((http|https):\/\/|www\.))[\w\.\'_%-]+(\+[\w-]*)?@([\w-]+\.)+[\w-]+$" );
```

**Review by nateh777 — CHANGES_REQUESTED** [review]
This is an untested change as it would fail using `emailString` instead of `email` the proper variable. I would prefer not to change the email Regex so drastically, though it might be cited as valid according to stack overflow it would require some testing. Which will require a test on a migration by us at a later time. If you would like a change to be made quicker I have added a suggested change to the regex that should accommodate the situation explained in the issue. If you can accept the suggestion and test it we can get this merged.

**Review by nateh777 — APPROVED** [review]
